### ISSUE TITLE
Arbitrary test failures

### ISSUE THREAD

**Issue by pepegar** [higherkindness/mu#289]
We've been conducting an investigation on the arbitrary failures we
have when testing bidirectional streaming with both
`monix.reactive.Observable` and `fs2.Stream`.

We've also seen that `fs2.Stream` based endpoints are much more likely to
fail than Observables, and that can be because we're making several
transformations under the hood:

```
fs2.Stream => fs2.interop.reactivestreams.StreamUnicastPublisher => monix.Observable
monix.Observable => org.reactivestreams.Publisher => fs2.Stream
```

Also, another finding is that [adding concurrency][] to the mix make
the tests much more likely to fail.

However, we don't have lots of clues about what's the root cause of
those problems. (or root causes...)

### 1. FS2 failing so often because of the unicast nature of the intermediate publisher

We're using [fs2-reactivestreams][] to convert fs2.Stream to
Publisher, but the only conversion available makes a unicast
publisher, allowing only one subscriber.
 
### Change the way we're integrating fs2

Currently every stream is converted to a publisher (via
[fs2-reactivestreams][]), and then to a monix observable before being
used in GRPC. We would like to try and see if [fs2-grpc][] helps.

[fs2-grpc]: https://github.com/fiadliel/fs2-grpc
[fs2-reactivestreams]: https://github.com/zainab-ali/fs2-reactive-streams 
[adding concurrency]: https://github.com/frees-io/freestyle-rpc/pull/284#issuecomment-393542444

---

Related issues:

#164, #282, #284 #376

**Comment by juanpedromoreno** [comment]
Is this fixed now? Could we close it?

**Comment by fedefernandez** [comment]
Yes, I didn't observed any failures related with this in the last builds

**Comment by pepegar** [comment]
Awesome! <3
