### ISSUE TITLE
Code Generation from Proto definitions

### ISSUE THREAD

**Issue by AdrianRaFo** [higherkindness/mu#379]
I'm trying to create `Scala` files from `proto` definitions but I'm getting this error:

`Unknown IDL type 'proto'. Valid values: avro`

My settings:

```
idlType := "proto",
srcGenSerializationType := "Protobuf",
srcGenTargetDir := (Compile / sourceManaged).value / "compiled_proto",
sourceGenerators in Compile += (srcGen in Compile).taskValue,
```

**Comment by juanpedromoreno** [comment]
Sadly, `frees-rpc` currently doesn't support code generation from proto files.

**Comment by AdrianRaFo** [comment]
Then the description is wrong 
```
lazy val idlType: SettingKey[String] =
      settingKey[String]("The IDL type to work with, such as avro or proto")
```

**Comment by AdrianRaFo** [comment]
Should be possible now with this https://github.com/AdrianRaFo/proton

**Comment by L-Lavigne** [comment]
This is currently being implemented in Skeuomorph, and will be integrated into the Mu source-gen sbt plugin.

Tracked at: https://github.com/higherkindness/skeuomorph/issues/30
