### ISSUE TITLE
AVDL to Scala: When generating tagged BigDecimals as Optionals the shapeless.@@ import is missing

### ISSUE THREAD

**Issue by fedefernandez** [higherkindness/mu#411]
When generating a tagged decimal from a field defined as nullable:

`union { decimal(8,2), null } field`

The Scala file generated doesn't include the `import shapeless.@@`

* Is an avrohugger problem?
* It happens with shapeless coproducts?

This happens since `0.15.1-SNAPSHOT`

**TBD**

**Comment by franciscodr** [comment]
Submitted a pull request to [avrohugger](https://github.com/julianpeeters/avrohugger) project that fixes the issue: https://github.com/julianpeeters/avrohugger/pull/105
