### ISSUE TITLE
BigDecimal tagged should be the default option in the SBT plugin

### ISSUE THREAD

**Issue by fedefernandez** [higherkindness/mu#468]
Currently, for keeping compatibility, the default value for the setting key `idlGenBigDecimal` is `ScalaBigDecimalGen` but we should have `ScalaBigDecimalTaggedGen` by default. It produces a better typing and uses `Avro` compliant serializer.

**Issue #411 should be fixed first**

**Comment by fedefernandez** [comment]
@juanpedromoreno thoughts?

**Comment by juanpedromoreno** [comment]
It makes sense to me :)
