### ISSUE TITLE
Code Coverage is broken

### ISSUE THREAD

**Issue by juanpedromoreno** [higherkindness/mu#476]
Current codecov reports are broken. We need to update it and ensure that the project is healthy in terms of test code coverage.

**Comment by fedefernandez** [comment]
The coverage gets executed and the reports look good but it seems codecov is not doing its job. I'll reopen this issue to take a look. 

For example: https://codecov.io/gh/higherkindness/mu/compare/f42402aec72b6c6ef9a74ff8a277acf25840bfe7...e8934d96cadfdae0878bf3f2b1fe26294667309d/tree/modules

**Comment by juanpedromoreno** [comment]
It seems this is fixed now. Thanks @fedefernandez .
