### ISSUE TITLE
Unused import warning

### ISSUE THREAD

**Issue by fedefernandez** [higherkindness/mu#491]
Currently, we add all the encoder imports without taking into account if they are needed. That causes a lot of warning messages like the following:
```bash
[warn] /Users/fede/development/workspaces/47deg/mu/modules/server/src/test/scala/protocol/Utils.scala:77:6: Unused import
[warn]     @service(Protobuf) trait ProtoRPCService[F[_]] {
```

It'd be nice to find a way of hiding those messages, by only adding the import when it's necessary or by adding some flag.

**Comment by pepegar** [comment]
Yeah, I think these warnings got introduced (by me) in the rewrite to paradise macros.

Lately, in droste macros I've been using FQCN, for avoiding imports and requiring implicits through method params instead of importing the whole package, I think it's a better approach

**Comment by fedefernandez** [comment]
I think this is not possible here since the algebra is agnostic to the protocol (and consequently to the encoders needed) and the client needs to fulfill the signature. Maybe I'm missing something.

**Comment by pepegar** [comment]
Lemme see if I can draft a PR :)

**Comment by pepegar** [comment]
Ah nope, the approach I tried doesn't work. I tried removing the encoders import from the macro altogether and importing explicitly in the file that declares the @service but nope.

**Comment by fedefernandez** [comment]
oh, thanks for trying
