### ISSUE TITLE
Client cache should receive a ManagedChannel

### ISSUE THREAD

**Issue by AdrianRaFo** [higherkindness/mu#563]
the client cache currently receives an `F[(Host, Port)]` and that's works for URL based services but if we choose to create a client using `ChannelFromTarget` we are not going to have the host and port. For that reason ideally, the client cache should receive the `F[ManagedChannel]` and work directly with that.

**Comment by mrtmmr** [comment]
Done
 https://github.com/higherkindness/mu/pull/617

**Comment by fedefernandez** [comment]
Thanks!
