### ISSUE TITLE
Docs - Review quickstart modules

### ISSUE THREAD

**Issue by fedefernandez** [higherkindness/mu#605]
The quickstart page shows incorrect artifact names. For example, the metrics are now split in two modules, dropwizard, and prometheus, but the page is still showing the ones with shared, client and server suffixes.

As part of this ticket, we should review all modules available in the 0.18.0 version and update that page accordingly.

**Comment by mrtmmr** [comment]
From the documentation I got they are optional functionalities, should we add a new section with some examples of Dropwizard  and Prometheus? 

I think the current (not deployed) version has already got updated from 0.18.0  to 0.18.3.

**Comment by fedefernandez** [comment]
> should we add a new section with some examples of Dropwizard and Prometheus?

That would be great.

> I think the current (not deployed) version has already got updated from 0.18.0 to 0.18.3.

Yes, but we have some artifact names that no longer exist, for example, `mu-rpc-prometheus-server`. We need to review all

**Comment by mrtmmr** [comment]
Documentation changed: #625
