### ISSUE TITLE
Best practices re: starting from Scala or starting from IDL

### ISSUE THREAD

**Issue by sander** [higherkindness/mu#608]
@juanpedromoreno wrote in https://github.com/higherkindness/mu/issues/604#issuecomment-486126067:
> > Not sure what you mean by "Scala protocols" since even when starting with "*.proto" the end result is Scala objects.
> 
> That's fine and that's the ideal pattern to use.
> 
> What I meant is that we shouldn't define the messages and services directly in Scala, by hand. If you do so, you might need to use them as jar dependencies in the client side, for example. This highly dangerous since you would be carrying on all the transitive dependencies from where the Scala protocol was defined. Therefore this might end with evictions and binary incompatibilities.
> 
> What would be the recommended pattern? Defining the protocol in IDL, so `sbt-mu-idlgen` plugin would generate the sources in every place, with the local dependencies in the project where you import the IDL definitions.

Just to have it clear for me as a user, does the Mu team recommend in general to

1. **always** start from `*.proto`, or
2. only start from `*.proto` if interoperability with non-Mu gRPC clients/servers is desired?

From http://higherkindness.io/mu/core-concepts#mu-rpc and http://higherkindness.io/mu/idl-generation it seems like the idiomatic way to use Mu is to handcraft messages and services in Scala, and IDL is just an extra feature for interoperability.

However, from this discussion I have the impression that the team now recommends to start from IDL instead. Is that true, and is it based on experiences with both approaches that you can share?

cc @fedefernandez @SemanticBeeng

**Comment by fedefernandez** [comment]
@sander I'm afraid that the documentation is a bit outdated on this matter. The project started with the approach of defining the messages and services in Scala but we find out that this could lead to binary incompatibilities, even if you're using `mu` in both, client and server.

Basically, using the protocols defined in Scala tie those protocols to a concrete `mu` version, so you need to keep always the client and the server on compatible versions. Defining your protocols in `proto` or `avdl` allows you to use different `mu` versions in the client and the server.

We need to reorganize the docs to have this clear, thanks for raising your concerns.

**Comment by mrtmmr** [comment]
The #621 PR (https://github.com/higherkindness/mu/pull/621) changed the documentation:

-New section created: Generate sources from IDL (IDL Generation separated into two sections)
-Added in Core Concepts' section a reference to Generate sources from IDL's new section
-References from "IDL Generation" changed to "Generate sources from IDL"
-IDL Generation tagged as deprecated
-"@message" code from "IDL Generation" and "Generate sources from IDL" dropped from other sections

I think it covers all the issues mentioned here.
