### ISSUE TITLE
Support gRPC health check endpoint by default

### ISSUE THREAD

**Issue by TannerYoung** [higherkindness/mu#626]
Mu should support gRPC health checks with limited configuration (if not by default) out of the box. See https://github.com/grpc/grpc/blob/master/doc/health-checking.md for details.

This would allow dependencies to wait for the service to become healthy before sending requests to it. For example https://github.com/grpc-ecosystem/grpc-health-probe/

This could be done with a default GrpcConfig implementation to be added as a parameter to configList in GrpcServer.netty[IO](port, myService :: healthService :: Nil).

**Comment by mrtmmr** [comment]
A first version of health check service: #630 
Pending:
 - Create new issue: "unary service part should support not only protobuf but avro" (https://github.com/higherkindness/mu/pull/630#issuecomment-516792561)
- Create healthcheck documentation (?)
