### ISSUE TITLE
Update mu-rpc-prometheus-server for 0.18.4

### ISSUE THREAD

**Issue by TannerYoung** [higherkindness/mu#673]
It looks like the [maven module](https://mvnrepository.com/artifact/io.higherkindness/mu-rpc-prometheus-server) hasn't been released for 0.18.4  but the artifact is still listed on the [mu web page](https://higherkindness.io/mu/)

Is this something that will be supported going forward or should I just create my own metrics reporter?

**Comment by fedefernandez** [comment]
@TannerYoung there is an error in that `mu` web page. The metrics were refactorized and the core metrics logic is delivered with the core libraries and the extra libraries you need to use are:

* [mu-rpc-prometheus](https://repo1.maven.org/maven2/io/higherkindness/mu-rpc-prometheus_2.12/)
* [mu-rpc-dropwizard](https://repo1.maven.org/maven2/io/higherkindness/mu-rpc-dropwizard_2.12/)

Depending on the backend you want to use.

Fortunately, the [guide for metrics](https://higherkindness.io/mu/metrics-reporting) is up to date, is just the module listing what is wrong. We'll update it ASAP, thanks for the heads up.

**Comment by TannerYoung** [comment]
Woo thank you for the quick response
